from __future__ import annotations

from io import StringIO

from rich.columns import Columns
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from devcard.extractors.activity import heatmap_sparkline
from devcard.extractors.languages import compute_coding_ratio
from devcard.models import DevCard

LANG_COLORS = {
    "C": "grey70",
    "C#": "green",
    "C++": "magenta",
    "CSS": "blue",
    "Dart": "cyan",
    "Go": "cyan",
    "HTML": "red",
    "Java": "red",
    "JavaScript": "yellow",
    "Jupyter Notebook": "orange3",
    "Kotlin": "magenta",
    "Lua": "blue",
    "PHP": "blue",
    "Python": "blue",
    "Ruby": "red",
    "Rust": "red",
    "Scala": "red",
    "Shell": "green",
    "Swift": "orange3",
    "TypeScript": "blue",
}


def render_terminal(devcard: DevCard) -> str:
    buf = StringIO()
    console = Console(file=buf, force_terminal=True, width=80)

    _render_header(console, devcard)
    if devcard.languages:
        _render_languages(console, devcard)
    if devcard.stack:
        _render_stack(console, devcard)
    if devcard.quality:
        _render_quality(console, devcard)
    if devcard.expertise and devcard.expertise.focus_areas:
        _render_focus(console, devcard)
    if devcard.activity:
        _render_activity(console, devcard)
    if devcard.projects:
        _render_projects(console, devcard)
    if devcard.enriched:
        _render_enriched(console, devcard)

    console.print(
        f"[dim]Generated by devcard v{devcard.generator.version} "
        f"at {devcard.generated_at.strftime('%Y-%m-%d %H:%M UTC')}[/]"
    )
    return buf.getvalue()


def _render_header(console: Console, devcard: DevCard) -> None:
    ident = devcard.identity
    parts = [f"[bold]{ident.name or ident.username}[/bold]  [dim]@{ident.username}[/dim]"]

    if devcard.expertise and devcard.expertise.profile_type:
        parts.append(f"  [cyan]{devcard.expertise.profile_type.replace('_', ' ').title()}[/]")

    if ident.bio:
        parts.append(f"\n{ident.bio}")

    meta = []
    if ident.location:
        meta.append(ident.location)
    if ident.company:
        meta.append(ident.company)
    if ident.followers:
        meta.append(f"{ident.followers:,} followers")
    if meta:
        parts.append(f"\n[dim]{' · '.join(meta)}[/]")

    console.print(Panel("".join(parts), border_style="blue"))


def _render_languages(console: Console, devcard: DevCard) -> None:
    lines = []
    for lang in devcard.languages[:8]:
        color = LANG_COLORS.get(lang.name, "white")
        bar_width = int(lang.percentage / 100 * 30)
        bar = "█" * bar_width + "░" * (30 - bar_width)
        lines.append(f"[{color}]{bar}[/] {lang.name} {lang.percentage:.1f}%")
    coding_ratio = compute_coding_ratio(devcard.languages)
    subtitle = f"Logic code: {coding_ratio:.0f}%"
    console.print(Panel(
        "\n".join(lines), title="Languages", subtitle=subtitle, border_style="green",
    ))


def _render_stack(console: Console, devcard: DevCard) -> None:
    stack = devcard.stack
    if stack is None:
        return
    sections = []
    for label, items in [
        ("Frameworks", stack.frameworks),
        ("Libraries", stack.libraries),
        ("Databases", stack.databases),
        ("Tools", stack.tools),
        ("Platforms", stack.platforms),
        ("CI/CD", stack.ci_cd),
        ("Testing", stack.testing),
    ]:
        if items:
            names = ", ".join(i.name for i in items[:8])
            sections.append(f"[bold]{label}:[/] {names}")
    if sections:
        console.print(Panel("\n".join(sections), title="Stack", border_style="yellow"))


def _render_quality(console: Console, devcard: DevCard) -> None:
    q = devcard.quality
    if q is None:
        return
    metrics = [
        ("Tests", q.test_adoption),
        ("CI/CD", q.ci_adoption),
        ("Docs", q.docs_adoption),
        ("License", q.license_adoption),
        ("Linter", q.linter_adoption),
    ]
    lines = []
    for name, val in metrics:
        filled = int(val * 20)
        bar = "█" * filled + "░" * (20 - filled)
        lines.append(f"{name:>8} [{_quality_color(val)}]{bar}[/] {val:.0%}")
    lines.append(f"\n[bold]Score: {q.score:.0%}[/]")
    if q.recommendations:
        lines.append("")
        for tip in q.recommendations[:3]:
            lines.append(f"[dim]→ {tip}[/]")
    console.print(Panel("\n".join(lines), title="Quality", border_style="magenta"))


def _quality_color(val: float) -> str:
    if val >= 0.7:
        return "green"
    if val >= 0.4:
        return "yellow"
    return "red"


def _render_focus(console: Console, devcard: DevCard) -> None:
    if devcard.expertise is None:
        return
    tags = []
    for area in devcard.expertise.focus_areas[:5]:
        tags.append(f"[bold cyan]{area.name}[/]")
    console.print(Panel(Columns(tags, padding=(0, 2)), title="Focus Areas", border_style="cyan"))


def _render_activity(console: Console, devcard: DevCard) -> None:
    act = devcard.activity
    if act is None:
        return
    status_colors = {"active": "green", "moderate": "yellow", "sporadic": "red", "dormant": "dim"}
    color = status_colors.get(act.status, "white")
    parts = [f"Status: [{color}]{act.status.upper()}[/]"]
    if act.consistency_score is not None:
        parts.append(f"Consistency: {act.consistency_score}/100")
    if act.peak_hours:
        hours_str = ", ".join(f"{h}:00" for h in act.peak_hours[:3])
        parts.append(f"Peak hours: {hours_str}")
    if act.timezone_estimate:
        parts.append(f"Timezone: {act.timezone_estimate}")
    if act.commits_last_year:
        parts.append(f"~{act.commits_last_year:,} commits/year (estimated)")
    lines = ["  |  ".join(parts)]
    if act.consistency_description:
        lines.append(f"[dim]{act.consistency_description}[/]")
    sparkline = heatmap_sparkline(act.heatmap)
    if sparkline:
        lines.append(f"[dim]{sparkline}[/]")
    console.print(Panel("\n".join(lines), title="Activity", border_style="green"))


def _render_projects(console: Console, devcard: DevCard) -> None:
    table = Table(title="Top Projects", border_style="blue", show_lines=False)
    table.add_column("Name", style="bold")
    table.add_column("Stars", justify="right")
    table.add_column("Forks", justify="right")
    table.add_column("Language")
    table.add_column("Status")

    for proj in devcard.projects[:8]:
        status_text = Text(proj.status or "unknown")
        if proj.status == "active":
            status_text.stylize("green")
        elif proj.status == "archived":
            status_text.stylize("dim")
        name = f"★ {proj.name}" if proj.is_signature else proj.name
        table.add_row(
            name,
            f"⭐ {proj.stars:,}" if proj.stars else "-",
            str(proj.forks) if proj.forks else "-",
            proj.language or "-",
            status_text,
        )
    console.print(table)
    sig = next((p for p in devcard.projects if p.is_signature and p.narrative), None)
    if sig:
        console.print(f"  [dim italic]{sig.narrative}[/]")


def _render_enriched(console: Console, devcard: DevCard) -> None:
    enriched = devcard.enriched
    if enriched is None:
        return
    lines: list[str] = []
    if enriched.archetype:
        lines.append(f"[bold cyan]🏷  {enriched.archetype}[/]")
    if enriched.summary:
        lines.append(f"\n{enriched.summary}")
    if enriched.strengths:
        lines.append("\n[bold]Strengths:[/]")
        for s in enriched.strengths:
            lines.append(f"  [green]✓[/] {s}")
    if enriched.suggestions:
        lines.append("\n[bold]Growth areas:[/]")
        for s in enriched.suggestions:
            lines.append(f"  [yellow]→[/] {s}")
    if enriched.project_highlights:
        lines.append("\n[bold]Project highlights:[/]")
        for h in enriched.project_highlights:
            badge = {"flagship": "⭐", "growing": "📈", "hidden gem": "💎"}.get(
                h.significance, "•"
            )
            lines.append(f"  {badge} [bold]{h.name}[/] — {h.reason}")
    console.print(Panel(
        "\n".join(lines), title="AI Insights", border_style="bright_magenta",
    ))
