from __future__ import annotations

from io import StringIO

from rich.columns import Columns
from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from devcard.extractors.activity import heatmap_sparkline
from devcard.extractors.languages import compute_coding_ratio
from devcard.models import DevCard

LANG_COLORS = {
    "C": "grey70",
    "C#": "green",
    "C++": "magenta",
    "CSS": "blue",
    "Dart": "cyan",
    "Go": "cyan",
    "HTML": "red",
    "Java": "red",
    "JavaScript": "yellow",
    "Jupyter Notebook": "orange3",
    "Kotlin": "magenta",
    "Lua": "blue",
    "PHP": "blue",
    "Python": "blue",
    "Ruby": "red",
    "Rust": "red",
    "Scala": "red",
    "Shell": "green",
    "Swift": "orange3",
    "TypeScript": "blue",
}


def render_terminal(devcard: DevCard) -> str:
    buf = StringIO()
    console = Console(file=buf, force_terminal=True, width=80)

    _render_header(console, devcard)
    if devcard.languages:
        _render_languages(console, devcard)
    if devcard.stack:
        _render_stack(console, devcard)
    if devcard.quality:
        _render_quality(console, devcard)
    if devcard.expertise and devcard.expertise.focus_areas:
        _render_focus(console, devcard)
    if devcard.activity:
        _render_activity(console, devcard)
    if devcard.projects:
        _render_projects(console, devcard)
    if devcard.collaboration and devcard.collaboration.notable_contributions:
        _render_notable(console, devcard)
    if devcard.coding_habits:
        _render_habits(console, devcard)
    if devcard.collaboration and devcard.collaboration.review_activity:
        _render_reviews(console, devcard)
    if devcard.lines_changed:
        _render_lines(console, devcard)
    if devcard.commit_quality:
        _render_commit_quality(console, devcard)
    if devcard.readme_depth:
        _render_readme_depth(console, devcard)
    if devcard.responsiveness:
        _render_responsiveness(console, devcard)
    if devcard.enriched:
        _render_enriched(console, devcard)

    console.print(
        f"[dim]Generated by devcard v{devcard.generator.version} "
        f"at {devcard.generated_at.strftime('%Y-%m-%d %H:%M UTC')}[/]"
    )
    return buf.getvalue()


def _render_header(console: Console, devcard: DevCard) -> None:
    ident = devcard.identity
    parts = [f"[bold]{ident.name or ident.username}[/bold]  [dim]@{ident.username}[/dim]"]

    if devcard.expertise and devcard.expertise.profile_type:
        parts.append(f"  [cyan]{devcard.expertise.profile_type.replace('_', ' ').title()}[/]")

    if ident.bio:
        parts.append(f"\n{ident.bio}")

    meta = []
    if ident.location:
        meta.append(ident.location)
    if ident.company:
        meta.append(ident.company)
    if ident.followers:
        meta.append(f"{ident.followers:,} followers")
    if meta:
        parts.append(f"\n[dim]{' · '.join(meta)}[/]")

    console.print(Panel("".join(parts), border_style="blue"))


def _render_languages(console: Console, devcard: DevCard) -> None:
    lines = []
    for lang in devcard.languages[:8]:
        color = LANG_COLORS.get(lang.name, "white")
        bar_width = int(lang.percentage / 100 * 30)
        bar = "█" * bar_width + "░" * (30 - bar_width)
        lines.append(f"[{color}]{bar}[/] {lang.name} {lang.percentage:.1f}%")
    coding_ratio = compute_coding_ratio(devcard.languages)
    subtitle = f"Logic code: {coding_ratio:.0f}%"
    console.print(Panel(
        "\n".join(lines), title="Languages", subtitle=subtitle, border_style="green",
    ))


def _render_stack(console: Console, devcard: DevCard) -> None:
    stack = devcard.stack
    if stack is None:
        return
    sections = []
    for label, items in [
        ("Frameworks", stack.frameworks),
        ("Libraries", stack.libraries),
        ("Databases", stack.databases),
        ("Tools", stack.tools),
        ("Platforms", stack.platforms),
        ("CI/CD", stack.ci_cd),
        ("Testing", stack.testing),
    ]:
        if items:
            names = ", ".join(i.name for i in items[:8])
            sections.append(f"[bold]{label}:[/] {names}")
    if sections:
        console.print(Panel("\n".join(sections), title="Stack", border_style="yellow"))


def _render_quality(console: Console, devcard: DevCard) -> None:
    q = devcard.quality
    if q is None:
        return
    metrics = [
        ("Tests", q.test_adoption),
        ("CI/CD", q.ci_adoption),
        ("Docs", q.docs_adoption),
        ("License", q.license_adoption),
        ("Linter", q.linter_adoption),
    ]
    lines = []
    for name, val in metrics:
        filled = int(val * 20)
        bar = "█" * filled + "░" * (20 - filled)
        lines.append(f"{name:>8} [{_quality_color(val)}]{bar}[/] {val:.0%}")
    lines.append(f"\n[bold]Score: {q.score:.0%}[/]")
    if q.recommendations:
        lines.append("")
        for tip in q.recommendations[:3]:
            lines.append(f"[dim]→ {tip}[/]")
    console.print(Panel("\n".join(lines), title="Quality", border_style="magenta"))


def _quality_color(val: float) -> str:
    if val >= 0.7:
        return "green"
    if val >= 0.4:
        return "yellow"
    return "red"


def _render_focus(console: Console, devcard: DevCard) -> None:
    if devcard.expertise is None:
        return
    tags = []
    for area in devcard.expertise.focus_areas[:5]:
        tags.append(f"[bold cyan]{area.name}[/]")
    console.print(Panel(Columns(tags, padding=(0, 2)), title="Focus Areas", border_style="cyan"))


def _render_activity(console: Console, devcard: DevCard) -> None:
    act = devcard.activity
    if act is None:
        return
    status_colors = {"active": "green", "moderate": "yellow", "sporadic": "red", "dormant": "dim"}
    color = status_colors.get(act.status, "white")
    parts = [f"Status: [{color}]{act.status.upper()}[/]"]
    if act.consistency_score is not None:
        parts.append(f"Consistency: {act.consistency_score}/100")
    if act.peak_hours:
        hours_str = ", ".join(f"{h}:00" for h in act.peak_hours[:3])
        parts.append(f"Peak hours: {hours_str}")
    if act.timezone_estimate:
        parts.append(f"Timezone: {act.timezone_estimate}")
    if act.commits_last_year:
        parts.append(f"~{act.commits_last_year:,} commits/year (estimated)")
    lines = ["  |  ".join(parts)]
    if act.consistency_description:
        lines.append(f"[dim]{act.consistency_description}[/]")
    sparkline = heatmap_sparkline(act.heatmap)
    if sparkline:
        lines.append(f"[dim]{sparkline}[/]")
    console.print(Panel("\n".join(lines), title="Activity", border_style="green"))


def _render_projects(console: Console, devcard: DevCard) -> None:
    table = Table(title="Top Projects", border_style="blue", show_lines=False)
    table.add_column("Name", style="bold")
    table.add_column("Stars", justify="right")
    table.add_column("Forks", justify="right")
    table.add_column("Language")
    table.add_column("Status")

    for proj in devcard.projects[:8]:
        status_text = Text(proj.status or "unknown")
        if proj.status == "active":
            status_text.stylize("green")
        elif proj.status == "archived":
            status_text.stylize("dim")
        name = f"★ {proj.name}" if proj.is_signature else proj.name
        table.add_row(
            name,
            f"⭐ {proj.stars:,}" if proj.stars else "-",
            str(proj.forks) if proj.forks else "-",
            proj.language or "-",
            status_text,
        )
    console.print(table)
    sig = next((p for p in devcard.projects if p.is_signature and p.narrative), None)
    if sig:
        console.print(f"  [dim italic]{sig.narrative}[/]")


def _render_commit_quality(console: Console, devcard: DevCard) -> None:
    cq = devcard.commit_quality
    if cq is None:
        return
    lines = [
        f"[bold]Avg message length:[/] {cq.avg_message_length:.0f} chars",
        f"[bold]Conventional commits:[/] {cq.conventional_commits_pct:.0f}%",
        f"[bold]Multi-line messages:[/] {cq.multiline_pct:.0f}%",
        f"[dim]{cq.commits_analyzed} commits analyzed[/]",
    ]
    console.print(Panel("\n".join(lines), title="Commit Quality", border_style="bright_yellow"))


def _render_readme_depth(console: Console, devcard: DevCard) -> None:
    rd = devcard.readme_depth
    if rd is None:
        return
    lines = [
        f"[bold]Avg words:[/] {rd.avg_word_count:.0f}  "
        f"[bold]Avg headings:[/] {rd.avg_heading_count:.1f}",
        f"[bold]Has code blocks:[/] {rd.has_code_blocks_pct:.0f}%  "
        f"[bold]Has images:[/] {rd.has_images_pct:.0f}%",
        f"[bold]Has install section:[/] {rd.has_install_section_pct:.0f}%",
        f"[dim]{rd.repos_analyzed} READMEs analyzed[/]",
    ]
    console.print(Panel("\n".join(lines), title="README Depth", border_style="bright_magenta"))


def _render_responsiveness(console: Console, devcard: DevCard) -> None:
    resp = devcard.responsiveness
    if resp is None:
        return
    parts = []
    if resp.issue_comments:
        parts.append(f"[bold]Issue comments:[/] {resp.issue_comments}")
    if resp.pr_comment_count:
        parts.append(f"[bold]PR comments:[/] {resp.pr_comment_count}")
    if resp.avg_response_hours is not None:
        parts.append(f"[bold]Avg response:[/] {resp.avg_response_hours:.1f}h")
    if parts:
        console.print(Panel("\n".join(parts), title="Responsiveness", border_style="bright_green"))


def _render_habits(console: Console, devcard: DevCard) -> None:
    habits = devcard.coding_habits
    if habits is None:
        return
    lines = []
    if habits.indentation:
        lines.append(f"[bold]Indentation:[/] {habits.indentation} "
                      f"(tabs: {habits.tabs_count}, spaces: {habits.spaces_count})")
    if habits.avg_line_length is not None:
        lines.append(f"[bold]Avg line length:[/] {habits.avg_line_length:.0f} chars")
    lines.append(f"[dim]{habits.lines_analyzed:,} lines analyzed[/]")
    console.print(Panel("\n".join(lines), title="Coding Habits", border_style="yellow"))


def _render_reviews(console: Console, devcard: DevCard) -> None:
    if devcard.collaboration is None:
        return
    review = devcard.collaboration.review_activity
    if review is None:
        return
    parts = [f"[bold]Reviews given:[/] {review.reviews_given}"]
    breakdown = []
    if review.approved:
        breakdown.append(f"[green]✓ {review.approved} approved[/]")
    if review.changes_requested:
        breakdown.append(f"[yellow]✎ {review.changes_requested} changes requested[/]")
    if review.commented:
        breakdown.append(f"[blue]💬 {review.commented} commented[/]")
    if breakdown:
        parts.append("  ".join(breakdown))
    if review.repos_reviewed:
        parts.append(f"[dim]Repos: {', '.join(review.repos_reviewed[:5])}[/]")
    console.print(Panel("\n".join(parts), title="Code Reviews", border_style="bright_blue"))


def _render_lines(console: Console, devcard: DevCard) -> None:
    lc = devcard.lines_changed
    if lc is None:
        return
    summary = f"[green]+{lc.total_added:,}[/] added  [red]-{lc.total_deleted:,}[/] deleted"
    if lc.by_repo:
        table = Table(show_header=True, border_style="dim", show_lines=False)
        table.add_column("Repo", style="bold")
        table.add_column("Added", justify="right", style="green")
        table.add_column("Deleted", justify="right", style="red")
        for rl in lc.by_repo[:5]:
            table.add_row(rl.repo, f"+{rl.added:,}", f"-{rl.deleted:,}")
        from rich.console import Group
        content = Group(summary, table)
        console.print(Panel(content, title="Lines Changed", border_style="bright_green"))
    else:
        console.print(Panel(summary, title="Lines Changed", border_style="bright_green"))


def _render_notable(console: Console, devcard: DevCard) -> None:
    if devcard.collaboration is None:
        return
    notables = devcard.collaboration.notable_contributions
    if not notables:
        return
    table = Table(title="Notable Contributions", border_style="bright_cyan", show_lines=False)
    table.add_column("Repository", style="bold")
    table.add_column("Stars", justify="right")
    table.add_column("Type")
    table.add_column("Count", justify="right")

    for nc in notables[:8]:
        type_label = nc.contribution_type.replace("_", " ").title()
        stars_str = f"⭐ {nc.repo_stars:,}"
        count_str = str(nc.count)
        if nc.merged is not None:
            count_str += f" ({nc.merged} merged)"
        table.add_row(nc.repo, stars_str, type_label, count_str)
    console.print(table)


def _render_enriched(console: Console, devcard: DevCard) -> None:
    enriched = devcard.enriched
    if enriched is None:
        return
    lines: list[str] = []
    if enriched.archetype:
        lines.append(f"[bold cyan]🏷  {enriched.archetype}[/]")
    if enriched.summary:
        lines.append(f"\n{enriched.summary}")
    if enriched.strengths:
        lines.append("\n[bold]Strengths:[/]")
        for s in enriched.strengths:
            lines.append(f"  [green]✓[/] {s}")
    if enriched.suggestions:
        lines.append("\n[bold]Growth areas:[/]")
        for s in enriched.suggestions:
            lines.append(f"  [yellow]→[/] {s}")
    if enriched.project_highlights:
        lines.append("\n[bold]Project highlights:[/]")
        for h in enriched.project_highlights:
            badge = {"flagship": "⭐", "growing": "📈", "hidden gem": "💎"}.get(
                h.significance, "•"
            )
            lines.append(f"  {badge} [bold]{h.name}[/] — {h.reason}")
    console.print(Panel(
        "\n".join(lines), title="AI Insights", border_style="bright_magenta",
    ))
